import type {Metadata} from "next";
import "./globals.css";
import Wrapper from "@/components/wrapper/Wrapper";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`antialiased`}
        >
        <Wrapper>
            <Header/>
        </Wrapper>
        {children}
        </body>
        </html>
    );
}
