import type {Metadata} from "next";
import "./globals.css";
import Wrapper from "@/components/wrapper/Wrapper";
import Header from "@/components/header/Header";
import { Poppins, Nunito, Philosopher, Quicksand, Monomakh } from "next/font/google";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    display: "swap",
    variable: "--font-poppins", // 👈 important
});
const nunito = Nunito({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"], // choose what you need
    display: "swap",
    variable: "--font-nunito", // 👈 important
});
// const monomakh = Monomakh({
//     subsets: ["latin"],
//     weight: ["400"], // choose what you need
//     display: "swap",
//     variable: "--font-monomakh", // 👈 important
// });
const quicksand = Quicksand({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"], // choose what you need
    display: "swap",
    variable: "--font-quicksand", // 👈 important
});
const philosopher = Philosopher({
    subsets: ["latin"],
    weight: ["400", "700"], // choose what you need
    display: "swap",
    variable: "--font-philosopher", // 👈 important
});


export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body
            className={`antialiased ${poppins.variable}
        ${nunito.variable}
        ${quicksand.variable}
        ${philosopher.variable}`}
        >
        <Wrapper>
            <Header/>
        </Wrapper>
        {children}
        </body>
        </html>
    );
}
